#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 17 14:53:13 CET 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim box_coeff_tb_behav -key {Behavioral:sim_1:Functional:box_coeff_tb} -tclbatch box_coeff_tb.tcl -view /home/sg24duk/vivadoworkspace/guided_filter/box_top_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/coeff_ak_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/coeff_top_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/box_coeff_tb_behav.wcfg -log simulate.log"
xsim box_coeff_tb_behav -key {Behavioral:sim_1:Functional:box_coeff_tb} -tclbatch box_coeff_tb.tcl -view /home/sg24duk/vivadoworkspace/guided_filter/box_top_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/coeff_ak_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/coeff_top_tb_behav.wcfg -view /home/sg24duk/vivadoworkspace/guided_filter/box_coeff_tb_behav.wcfg -log simulate.log

